import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import NavBar from "./NavBar";
import SidebarContextProvider from "@/context/sidebar-context";
import SideBar from "./SideBar";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <SidebarContextProvider>
          <div className="flex h-screen  overflow-hidden">
            <SideBar />
            <div className="flex flex-col w-full h-full overflow-hidden ">
              <NavBar />
              <main>{children}</main>
            </div>
          </div>
        </SidebarContextProvider>
      </body>
    </html>
  );
}
